import type { BindColumn } from './bindColumns.types';

/** Client-side sample columns when schema source is manual (suggestions pending until accepted). */
export const BIND_SAMPLE_COLUMNS: BindColumn[] = [
  {
    col: 'trade_id',
    type: 'VARCHAR',
    len: '30',
    nul: 'No',
    vals: '',
    srcmap: 'endur.trade_id',
    orig: 'No Transformation',
    pii: 'No',
    suggest: '',
    method: 's',
    suggestedBde: 'Trade Identifier (BDE_D001)',
    xform: 'Straight copy',
  },
  {
    col: 'notional_amt',
    type: 'DECIMAL',
    len: '18,2',
    nul: 'No',
    vals: '>= 0',
    srcmap: 'endur.notional',
    orig: 'Derived/Transformed',
    pii: 'No',
    suggest: '',
    method: 's',
    suggestedBde: 'Notional Amount (BDE_D008)',
    xform: 'Straight copy',
  },
  {
    col: 'trade_dt',
    type: 'DATE',
    len: '',
    nul: 'No',
    vals: 'ISO 8601',
    srcmap: 'endur.trade_date',
    orig: 'No Transformation',
    pii: 'No',
    suggest: '',
    method: 's',
    suggestedBde: 'Trade Date (BDE_D065)',
    xform: 'Straight copy',
  },
  {
    col: 'cpty_id',
    type: 'CHAR',
    len: '18',
    nul: 'No',
    vals: '',
    srcmap: 'endur.cpty_id',
    orig: 'No Transformation',
    pii: 'No',
    suggest: '',
    method: 's',
    suggestedBde: 'Counterparty Identifier (BDE_D044)',
    xform: 'Straight copy',
  },
  {
    col: 'cpty_lei',
    type: 'CHAR',
    len: '20',
    nul: 'Yes',
    vals: 'ISO 17442',
    srcmap: 'endur.cpty_lei',
    orig: 'No Transformation',
    pii: 'Yes',
    suggest: '',
    method: 'n',
    suggestedBde: '',
    xform: 'Straight copy',
  },
  {
    col: 'internal_flag',
    type: 'BOOLEAN',
    len: '',
    nul: 'Yes',
    vals: 'Y | N',
    srcmap: 'endur.internal',
    orig: 'Manually Entered',
    pii: 'No',
    suggest: '',
    method: 'n',
    suggestedBde: '',
    xform: 'Straight copy',
  },
];

export function cloneBindColumns(rows: BindColumn[]): BindColumn[] {
  return rows.map((r) => ({ ...r }));
}
