import type { BulkPdeRow } from './bulkPde.types';

/**
 * Built-in sample rows for “Preview sample data” (validation demo only).
 * Not registered — users must upload a real CSV to register.
 */
export const BULK_PDE_SAMPLE_ROWS: BulkPdeRow[] = [
  {
    dataset: 'Endur FX Forwards',
    column: 'fx_deal_id',
    type: 'VARCHAR',
    length: '30',
    nullable: 'No',
    pii: 'No',
    sourceMapping: 'Endur.DEAL.DEAL_ID',
    validValues: '',
    description: 'Unique FX deal reference',
  },
  {
    dataset: 'Endur FX Forwards',
    column: 'ccy_pair',
    type: 'CHAR',
    length: '6',
    nullable: 'No',
    pii: 'No',
    sourceMapping: 'Endur.DEAL.CCY_PAIR',
    validValues: 'ISO 4217 pair',
    description: 'Currency pair',
  },
  {
    dataset: 'Endur FX Forwards',
    column: 'notional_base',
    type: 'DECIMAL',
    length: '18,2',
    nullable: 'No',
    pii: 'No',
    sourceMapping: 'Endur.DEAL.NOTIONAL',
    validValues: '>0',
    description: 'Base notional amount',
  },
  {
    dataset: 'Endur FX Forwards',
    column: 'fwd_rate',
    type: 'DECIMAL',
    length: '12,6',
    nullable: 'No',
    pii: 'No',
    sourceMapping: 'Endur.DEAL.FWD_RATE',
    validValues: '>0',
    description: 'Forward rate',
  },
  {
    dataset: 'Endur FX Forwards',
    column: 'value_date',
    type: 'DATE',
    length: '',
    nullable: 'No',
    pii: 'No',
    sourceMapping: 'Endur.DEAL.VAL_DT',
    validValues: '',
    description: 'Settlement date',
  },
  {
    dataset: 'Endur FX Forwards',
    column: 'trader_name',
    type: 'VARCHAR',
    length: '80',
    nullable: 'Yes',
    pii: 'Yes',
    sourceMapping: 'Endur.DEAL.TRADER',
    validValues: '',
    description: 'Executing trader',
  },
  {
    dataset: 'Endur FX Forwards',
    column: '',
    type: 'DECIMAL',
    length: '18,2',
    nullable: 'No',
    pii: 'No',
    sourceMapping: '',
    validValues: '',
    description: 'Missing column name',
  },
];
